### ISSUE TITLE
How to read raw depth image

### ISSUE THREAD

**Issue by lanfeiying** [tum-vision/rgbd_scribble_benchmark#2]
Hi,
I am using TUM benchmark dataset.
When I use C++ (OpenCV) to read the raw depth image, I found `.png` files are 8 bits, 3 channels.

For example:
```
//here, depth_image is CV_8UC3
cv::Mat depth_image = cv::imread(filename);
```
I read the introduction of the dataset, it says depth map is stored as 16 bits.
Can I ask how to read 16-bit depth map from 8-bit, 3 channels .png files?
In other words, how is 16-bit depth value stored in 8-bit `.png` files? Even though it has 3 channels.

**Comment by hazirbas** [comment]
Hey, you can set the flag in `cv::imread(filename, cv::IMREAD_UNCHANGED )` and then divide the depth with `1000.` for values in meters.
